config/routes.rb
ShoppeWebsite::Application.routes.draw do
  
  get 'features' => 'pages#features'
  
  get 'docs' => 'documentation#index'
  get 'docs/*path' => 'documentation#page', :as => 'docs_page'
  
  get 'code' => 'pages#code'
  get 'code/release-notes' => 'pages#release_notes', :as => 'code_release_notes'
  get 'code/modules' => 'pages#modules'  

  get 'support' => 'pages#support'
  get 'support/involvement' => 'pages#involvement'
  get 'support/commercial' => 'pages#commercial_support'
  get 'support/development' => 'pages#development'
  
  get 'about' => 'pages#about'
  get 'about/partners' => 'pages#partners'
  get 'about/license' => 'pages#license'
  get 'about/contributing' => 'pages#contributing'
  get 'about/logos' => 'pages#logos'
  
  root :to => 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'page'
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  
  layout 'page'
  
  def page
    file =  Rails.root.join('docs', params[:path].gsub(/[^a-z0-9\-\/]+/, '') + ".md")
    if File.exist?(file)
      @markdown = File.read(file)
    else
      head :ok, 'X-Cascade' => 'pass'
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    render :layout => 'home'
  end
  
  def release_notes
    notes_path = Rails.root.join('db', 'CHANGELOG.md')
    if File.exist?(notes_path)
      @notes = File.read(notes_path)
    else
      @notes = ''
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def link_to(name = nil, options = {}, html_options = {}, &block)
    if html_options[:nav_item] && @active_nav == html_options.delete(:nav_item)
      html_options[:class] ? html_options[:class] << " active" : html_options[:class] = "active"
    end
    super
  end
  
  def markdown(text)
    text = text.gsub(/\{\{partial\:(\w+)\}\}/) do
      render :partial => "documentation/#{$1}"
    end
    
    markdown = Redcarpet::Markdown.new(Shoppe::MarkdownRenderer, :fenced_code_blocks => true, :autolink => true, :space_after_headers => true)
    html = markdown.render(text).html_safe
    html
  end
  
end

app/views/documentation/_getting_started_series.html.haml
%div.series
  %p.more= link_to "More info", docs_page_path('tutorials/getting-started')
  %p Part of the <b>Getting Started with Shoppe series</b>
    

app/views/documentation/_nav.html.haml
%nav
  %ul
    %li= link_to "Welcome", docs_path, :class => action_name == 'index' && 'active'
  %h3 Getting Started Series
  %ul
    %li= link_to "Setting up Shoppe", docs_page_path('tutorials/setting-up'), :class => action_name == 'page' && params[:path] == 'tutorials/setting-up' && 'active'
    %li= link_to "Displaying Products", docs_page_path('tutorials/products'), :class => action_name == 'page' && params[:path] == 'tutorials/products' && 'active'
    %li= link_to "Baskets", docs_page_path('tutorials/baskets'), :class => action_name == 'page' && params[:path] == 'tutorials/baskets' && 'active'
    %li= link_to "Checking out", docs_page_path('tutorials/checking-out'), :class => action_name == 'page' && params[:path] == 'tutorials/checking-out' && 'active'
  %h3 Further reading
  %ul
    %li= link_to "Payment Gateways", docs_page_path('tutorials/payment-gateways'), :class => action_name == 'page' && params[:path] == 'tutorials/payment-gateways' && 'active'
    %li= link_to "Extending Shoppe", docs_page_path('extending'), :class => action_name == 'page' && params[:path] == 'extending' && 'active'
    %li= link_to "Tips & Tricks", docs_page_path('tips'), :class => action_name == 'page' && params[:path] == 'tips' && 'active'
    %li= link_to "API Documentation", "http://api.tryshoppe.com"

app/views/documentation/index.html.haml
- @active_nav = :docs
- @page_title = "Docs & Tutorials"

%section.docs
  .inner
    = render 'nav'
    
    %section.main
      %h2 Docs & Tutorials
      %p
        Welcome to the documentation & tutorials section of the Shoppe website. In here we 
        hope you'll find an array of useful documents and tips to help you get started with
        Shoppe in your Rails application.
        
      %p.iconed.new
        If you're <b>new to Shoppe</b>, get started by checking our our #{link_to "getting started tutorials", docs_page_path('tutorials/getting-started')}
        which will guide you through setting up a new application. This then follows onto how to
        create controllers and build views for your shop.
      
      %p.iconed.experienced
        If you've <b>already got some experience</b> with Shoppe, you may want to take a look at our
        #{link_to 'generated API documentation', 'http://api.tryshoppe.com'} which is generated
        from the Shoppe source code automatically when new versions are deployed.
      
      %p.iconed.payments
        Alternatively, if you <b>want add support for a payment gateway</b>, the #{link_to 'payment gateway tutorial', docs_page_path('tutorials/payment-gateways')}
        may be of interest to you.

  .screenshot

app/views/documentation/page.html.haml
- @active_nav = :docs
- @page_title = "Docs & Tutorials"

%section.docs
  .inner
    = render 'nav'
    
    %section.main
      ~ preserve markdown(@markdown)
      
  .screenshot

app/views/layouts/home.html.haml
!!!
%html
  %head
    = render 'shared/head'
  %body
    %header.home
      .inner
        = render 'shared/nav'
        %div.screenshot= image_tag 'screenshot.png'
        %section.welcome
          %h2 <b>Shoppe.</b> The open source e-commerce platform for Ruby on Rails.
          %h3 The complete solution for anyone who wants to develop an online shop and doesn’t fancy over complication or extortionate monthly subscriptions & transaction costs.
          %ul.buttons
            %li= link_to "Check out the demo", 'http://demo.tryshoppe.com', :class => 'demo'
            %li= link_to "Read our docs & get started", docs_path, :class => 'docs'
    = yield
    = render 'shared/footer'

app/views/layouts/page.html.haml
!!!
%html
  %head
    = render 'shared/head'
  %body
    %header.page
      .inner
        = render 'shared/nav'
    %section.page
      = yield :banner
      = yield
    = render 'shared/footer'
    

app/views/pages/_code_nav.html.haml
- @active_nav = :code
= content_for :banner do
  .banner.code
    %nav.page.four
      .inner
        %ul
          %li
            %a{:href => code_path}
              %h4 Our repositories
              %p Details of the main Shoppe Git repositories
              - if action_name == 'code'
                .arrow
          %li
            %a{:href => code_release_notes_path}
              %h4 Release notes
              %p Full details about changes in each version of Shoppe
              - if action_name == 'release_notes'
                .arrow
          %li
            %a{:href => 'https://github.com/tryshoppe/core/issues'}
              %h4 Issue tracker
              %p Browse all the existing bugs & feature requests submitted
          %li
            %a{:href => code_modules_path}
              %h4 Modules
              %p Details about the various modules which are available
              - if action_name == 'modules'
                .arrow

app/views/pages/_support_nav.html.haml
- @active_nav = :support
.banner.support
  %nav.page.four
    .inner
      %ul 
        %li
          %a{:href => support_path}
            %h4 Bugs, Features & Security
            %p How to report bugs & request features 
            - if action_name == 'support'
              .arrow
        %li
          %a{:href => support_involvement_path}
            %h4 Get involved
            %p Details about our mailing list, IRC channel, blog & Twitter
            - if action_name == 'involvement'
              .arrow
        %li
          %a{:href => support_commercial_path}
            %h4 Commercial support
            %p Get assistance with your Shoppe development
            - if action_name == 'commercial_support'
              .arrow
        %li
          %a{:href => support_development_path}
            %h4 Module development
            %p Order custom module development for Shoppe
            - if action_name == 'development'
              .arrow

app/views/pages/about.html.haml
- @page_title = "About"
= render 'about_nav'

%section.content
  .inner
    .sub
    .main
      %h2 About Shoppe
      %p
        Shoppe is a Rails engine which provides all the functionality need to build an e-commerce site using Ruby on Rails.
        It has been developed out of the need for a solid and reliable platform to sell physical goods for a small company in the
        United Kingdom.
        
      %h3 Who should use Shoppe?
      %p
        Shoppe is a tool for developers who need to develop a shop. To get up and running there is a requirement
        to build a Rails application to handle your store's customer interaction. We recommend you have some 
        experience with Ruby on Rails before getting started however our tutorials will help Rails beginners get
        up and running a few hours (or less).
      
      %h3 What's with the name?
      %p
        Shoppe is a deliberately archaized spelling of Shop and it pronouced in exactly the same way. We often
        hear people referring to Shoppe as "shop-y" which is wrong - please don't do that.
      
      %h3 The core team
      %p
        There isn't much of a team at present. To date, Shoppe has been pretty much entirely developed by 
        #{link_to 'Adam Cooke', 'http://adamcooke.io'}, a UK-based Ruby on Rails developer who runs a few
        companies in the UK, including #{link_to 'Niftyware', 'http://niftyware.io'} & #{link_to 'aTech Media', 'http://atechmedia.com'}.
        Hopefully over time, the team list below will grow as the core team expands.

      %ul.team
        %li
          = gravatar "adam@niftyware.io", :size => 128
          %h4= link_to "Adam Cooke", "http://adamcooke.io"
          %p Lead developer & designer
          
        %li
          = image_tag "user.png", :width => 128
        %li
          = image_tag "user.png", :width => 128
          

app/views/pages/code.html.haml
- @page_title = "Code"
= render 'code_nav'

%section.content
  .inner
    .sub
    .main
      %h2 The Shoppe code repositories
      %p 
        We have two main repositories which may be of interest to you. As Shoppe itself
        is just an engine, it has it's own repository which can be included into any
        Rails application through a RubyGem. Additionally, we also have a full Rails 
        application (our demo store) which can be used as a basis for any new store
        if you don't wish to start from scratch.
      
      %section.iconed.code.core
        %p.badge= link_to image_tag("https://badge.fury.io/rb/shoppe.png"), "http://rubygems.org/gems/shoppe"
        %h3 The core repository
        %p
          The core repository contains all the Shoppe models, admin UI and logic needed
          to run your store. Unless your contributing to the core project, you won't 
          need make any changes to this. This repository is packed up as a RubyGem
      
        %p.buttons
          = link_to "Browse files", "https://github.com/tryshoppe/core"
          = link_to "View commits", "https://github.com/tryshoppe/core/commits"
          = link_to "Check out the RubyGem", "http://rubygems.org/gems/shoppe"
      
      %section.iconed.code.demo
        %h3 The example/demo site
        %p
          The example/demo Rails application provides a fully working, fully integrated,
          Shoppe store which can be used as the basis for a new application. 
        %p.buttons
          = link_to "Browse files", "https://github.com/tryshoppe/example-store"
          = link_to "View commits", "https://github.com/tryshoppe/example-store/commits"
          = link_to "See it in action", "http://demo.tryshoppe.com"
        

app/views/pages/commercial_support.html.haml
- @page_title = 'Commercial technical support - Support'
= render 'support_nav'

%section.content
  .inner
    .sub
      %ul.largeButtons
        %li.ticket
          %a{:href => '#'}
            %h4 Create a ticket
            %p Submit an support request to our core development team
        %li.ticket-status
          %a{:href => '#'}
            %h4 Check status
            %p Check the status of an outstanding Shoppe support ticket

    .main
      %h2 Commercial technical support
      %p
        We offer a paid-for technical support service for anyone who is struggling with developing or
        deploying Shoppe. Obviously, if you think you've found a bug we will happily discuss these things
        with you through GitHub issues. If you have an implementation issue or a question, we charge a
        fee of only <b>$80 per ticket</b> with a Shoppe core developer.
      
      %p
        Once you've paid for your ticket, there are no limits on the number of messages you can send
        us about the same issue. All communications will happen by e-mail to the address you give
        when you submit your first ticket.
      
      %p
        We don't provide any SLA for this service but we will always aim to reply to tickets within
        24 hours.
        
      %p
        To get submit a ticket, just use the button on the right to get started.

app/views/pages/contributing.html.haml
- @page_title = "Contributing - About"
= render 'about_nav'

%section.content
  .inner
    .main

      %h2 Contributing to Shoppe

      %p
        Up until now, Shoppe has been developed exclusively by #{link_to 'Adam Cooke', 'http://adamcooke.io'},
        while working at #{link_to 'Niftyware', 'http://niftyware.io'}, however 
        if anyone else wants to get in on the action - we'd love to hear from you.


      %section.iconed.contributing.code

        %h3 Contributing to the codebase
        %p
          We'd love to accept contributions from developers all over the world.
          If you'd like to contribute to the Shoppe project, just 
          #{link_to 'submit a pull request', 'https://help.github.com/articles/using-pull-requests'}
          to the appropriate #{link_to 'GitHub repository', 'http://github.com/tryshoppe'}.

        %p
          If you're interested in joining our core development team, we'd also love
          to hear from you. Please drop us a message on one of our social networks
          (in the footer) and we'll get back to you.

      %section.iconed.contributing.design
        %h3 Contributing to the UI design
        %p
          If you're a designer and would like to suggest changes to the Shoppe admin 
          interface, that'd be fantastic too. Just send us your ideas and we can get
          them integrated into the project.
      
      %section.iconed.contributing.documentation
        %h3 Contributing to the documentation
        %p
          One of the most important things to this project is ensuring the documentation
          is the best we can make it. If you're excellent with words and can provide
          tutorials or documentation improvements, we'd love some help.
        %p
          The documentation on this website is all #{link_to 'hosted on GitHub', 'https://github.com/tryshoppe/documentation'}
          so if you have any suggestions or new tutorials, please feel free to submit a pull request.
      
      %section.iconed.contributing.other
        %h3 Contributing in other ways
        %p
          If there's something else you feel you can contribute, don't hesitate to 
          get in touch!

app/views/pages/development.html.haml
- @page_title = 'Custom module development - Support'
= render 'support_nav'

%section.content
  .inner
    .sub
      %ul.largeButtons
        %li.quote
          %a{:href => 'mailto:development@tryshoppe.com'}
            %h4 Request Quote
            %p Contact us for an estimate for your custom development
    
    .main
      %h2 Custom module development
      %p
        We're here to help if you need to integrate with unsupported payment gateways or 
        other third-party applications. Our custom module development service will create a
        module for your Shoppe store to do exactly what you need.
      
      %h3 License
      %p 
        We ask that custom development carried out by us is licensed under the same license as 
        the Shoppe software. This isn't a requirement, you can keep your module to yourself, but
        we'd be forever grateful. 
      
      %h3 Pricing
      %p
        Module development prices start from $100/hour and an estimate will be provided before any
        work begins and we will need an upfront payment before any development work can commence.
        
      %h3 Example modules
      %p
        Extending Shoppe to integrate with any number of third party services is usually very simple.
      %ul.list 
        %li Additional payment gateways
        %li Integrations with external accounting software
        %li Integrations with drop shipping services
        %li Courier/Delivery service integrations and support

app/views/pages/home.html.haml
- @active_nav = :home
- @page_title = "The Ruby on Rails e-commerce platform"

%section.home
  
  %section.features
    .inner
      %ul
        %li.ui= link_to "Complete admin interface included"
        %li.rails= link_to "Built with Ruby on Rails"
        %li.design= link_to "Design your store however you want"
        %li.payments= link_to "Works with any payment gateway"
        %li.businesses= link_to "A platform with businesses in mind"
        %li.docs= link_to "Fantastic docs & tutorials"
        %li.support= link_to "Commercial support & development"
  
  %section.featureBoxes
    .inner
      %ul
        %li.rails
          .arrow
          %h3 <b>A Rails 4.0 engine.</b> You build the frontend, we'll hand the rest.
          %p Shoppe is an engine which is easily inserted into an existing or new #{link_to 'Ruby on Rails', 'http://rubyonrails.org'} 4.0 application. You simply create your store’s frontend and we'll provide the backend and all the models needed to keep everything together.
  
  %section.partners
    .inner
      %h4 Shoppe couldn’t happen without the generous supoprt of our sponsors
      %ul
        %li.deploy= link_to "Deploy", "http://www.deployhq.com"
        %li.atech= link_to "aTech Media", "http://atechmedia.com"
        %li.niftyware= link_to "Niftyware", "http://niftyware.io"
        %li.codebase= link_to "Codebase", "http://www.codebasehq.com"
        %li.deliver= link_to "Deliver", "http://www.deliverhq.com"

app/views/pages/license.html.haml
- @page_title = "License - Shoppe"
= render 'about_nav'
%section.content
  .inner
    .main

      %h2 The MIT License
      %p
        Shoppe is licensed under the #{link_to 'MIT Licence', 'http://en.wikipedia.org/wiki/MIT_License'}
        which is the same license used for the Ruby on Rails project. We feel this
        give everyone the most flexibility to do whatever they wish with the
        software providing that the appropriate copyright notices stay in tact.
      %p
        The full licence as distributed with Shoppe is shown below:
      .license
        %p
          Copyright 2013 Niftyware Limited.
        %p
          Permission is hereby granted, free of charge, to any person obtaining
          a copy of this software and associated documentation files (the
          "Software"), to deal in the Software without restriction, including
          without limitation the rights to use, copy, modify, merge, publish,
          distribute, sublicense, and/or sell copies of the Software, and to
          permit persons to whom the Software is furnished to do so, subject to
          the following conditions:
        %p
          The above copyright notice and this permission notice shall be
          included in all copies or substantial portions of the Software.
        %p
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
          NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
          LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
          OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
          WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

app/views/pages/logos.html.haml
- @page_title = "Logos - Shoppe"
= render 'about_nav'

%section.content
  .inner
    .main

      %h2 The Shoppe Logo
      %p
        The Shoppe logomark is a simple affair featuing a mark and text. 
        We want to make usage of the logo as flexible as possible but we do need
        to protect the project so please read the guidelines below as to how and
        where you can use the logo. If you have any doubt, please just ask.

      %ul.logos
        %li.light= image_tag 'logo-full-white.svg'
        %li.dark= image_tag 'logo-full-black.svg'

      %p.download
        = link_to "Download logo pack &mdash; AI, SVG & PNG".html_safe, '/files/logos.zip', :class => 'button'
  

      %h3 Where can I use the Shoppe logo?
      %ul.logo-usage
        %li.ok You <b>may use</b> the logo when developing any Shoppe modules, documentation or other plugins
        %li.ok You <b>may use</b> the logo on your own website to convey knowledge and experience with the Shoppe platform.
        %li.bad You <b>may not use</b> the logo to suggest any "official link" with the the Shoppe project. For example, you may not publish a book called "The Official Guide to Shoppe" without permission.
        %li.bad You <b>may not use</b> the logo to suggest any endorsement by the developers or partners of Shoppe. For example, you may not refer to yourself as a "Shoppe Certified Developer".
        %li.bad You <b>may not use</b> the logo in order to raise money for any cause other than the official Shoppe development fund.
  

app/views/pages/modules.html.haml
- @page_title = "Modules - Code"
= render 'code_nav'

%section.content
  .inner
    .sub  
      %p.own-mod
        If you have developed a module and would like it listed either #{mail_to 'development@tryshoppe.com', 'contact us'}
        or #{link_to 'fork the website repo', 'http://github.com/tryshoppe/website'} and submit a pull request.
      
    .main
      %h2 The module store
      %p
        This page lists all the modules which are available for Shoppe at the present time. At the moment,
        we don't have too many of these so feel free to write some modules!

      %h3 Payment Processors
      %ul.modules
      
        %li
          %p.buttons
            = link_to "Repository", "http://github.com/tryshoppe/stripe"
            = link_to "Docs", "https://github.com/tryshoppe/stripe/blob/master/README.md"
          %h4= link_to "Stripe"
          %p.desc Integrate your Shoppe store with the Stripe payment processor.
      

app/views/pages/partners.html.haml
- @page_title = "Our partners - About"
= render 'about_nav'
%section.content
  .inner
    .main

      %h2 Our fantastic partners
      %p
        We just couldn't have developed Shoppe without the help from the partners listed
        below. Go and check out their sites, if you work with Rails we're sure you'll love
        their work!
  
      %ul.partners
        %li
          %h3= link_to image_tag('partners/niftyware.svg', :width => 200), "http://niftyware.io"
          %p
            = link_to "Niftyware", "http://niftyware.io"
            provide elegant software solutions for businesses focusing
            on support & billing software.
        %li
          %h3= link_to image_tag('partners/atech.svg', :width => 200), "http://atechmedia.com"
          %p
            = link_to "aTech Media", "http://atechmedia.com"
            are a UK-based Rails development company specialising in working
            with techs.
  

        %li
          %h3= link_to image_tag('partners/codebase.svg', :width => 200), "http://www.codebasehq.com"
          %p
            = link_to "Codebase", "http://www.codebasehq.com"
            is a code hosting solution for software development teams.
        %li
          %h3= link_to image_tag('partners/deploy.svg', :width => 140), "http://www.deployhq.com"
          %p
            = link_to "Deploy", "http://www.deployhq.com"
            is a web-based deployment platform for Git & Subversion repos
            with FTP, SFTP & the cloud.

        %li
          %h3= link_to image_tag('partners/deliver.svg', :width => 120), "http://www.deliverhq.com"
          %p
            = link_to "Deliver", "http://www.deliverhq.com"
            offers a world-class e-mail delivery platform for sending & receiving messages.

app/views/pages/release_notes.html.haml
- @page_title = "Release Notes - Code"
= render 'code_nav'
%section.content
  .inner
    .main
      %section.release-notes
        = markdown @notes

app/views/pages/support.html.haml
- @page_title = 'Bugs & Features - Support'
= render 'support_nav'

%section.content
  .inner
    .sub
      %ul.largeButtons
        %li.bug
          %a{:href => 'http://github.com/tryshoppe/core/issues/new'}
            %h4 Report a bug
            %p Use GitHub issues to report a bug with Shoppe
        %li.feature
          %a{:href => 'http://github.com/tryshoppe/core/issues/new'}
            %h4 Suggest feature
            %p Use GitHub issues to suggest features for Shoppe
        %li.security
          %a{:href => 'mailto:security@tryshoppe.com'}
            %h4 Security issue
            %p Drop us an e-mail to report security problems with Shoppe.

    .main
      %h2 Bugs, features & security issues
      %p
        If you think you've found a bug in Shoppe, we'd love to hear about it and discuss it with you.
        We handle all bug reports on our GitHub issues page so please head over there and
        submit the bug.
      %p
        If you'd like to request a feature to be added to the core Shoppe system, please add an issue on
        GitHub and we'll respond to your request as appropriate. If we believe an issue is worth adding 
        it will be left on the account and potentially assigned a milestone. If we believe your request is
        out of scope and module territory, it will be closed.
      %p
        If you find a security issue, we would rather you didn't post this publically until we have had
        a chance to issue a fix. If you do come across a sensitive issue, please drop us an email to
        #{mail_to 'security@tryshoppe.com'} and we'll look at it right away.

app/views/shared/_footer.html.haml
%footer.links
  .inner
    .column.copyright
      %p Shoppe is commercially supported by Niftyware Limited. A UK-based company, registration number 8514362.
      %p Copyright &copy; #{Date.today.year} Niftyware Limited.
      
    .column
      %h4 Quick links
      %ul
        %li= link_to "Features", features_path
        %li= link_to "Docs & Tutorials", docs_path
        %li= link_to "Live Demo", "http://demo.tryshoppe.com"
        %li= link_to "Support", support_path
        %li= link_to "About", about_path
    .column 
      %h4 Social
      %ul
        %li= link_to "Read our blog", "http://blog.tryshoppe.com"
        %li= link_to "Follow us on Twitter", "http://twitter.com/tryshoppe"
        %li= link_to "Check us out on GitHub", "http://github.com/tryshoppe"
        %li= link_to "Submit a support request", support_path

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-25967703-9', 'tryshoppe.com');
  ga('send', 'pageview');

app/views/shared/_head.html.haml
%title #{@page_title || 'Untitled Page'} - Shoppe
= stylesheet_link_tag :application
= javascript_include_tag :application
= csrf_meta_tags
<script type="text/javascript" src="//use.typekit.net/xiy2aid.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

app/views/shared/_nav.html.haml
%nav.primary
  %h1= link_to 'Shoppe', root_path
  %ul
    %li.demo= link_to "Try the demo", "http://demo.tryshoppe.com"
    %li= link_to "Home", root_path, :nav_item => :home
    %li= link_to "Features", features_path, :nav_item => :features
    %li= link_to "Docs & Tutorials", docs_path, :nav_item => :docs
    %li= link_to "Code", code_path, :nav_item => :code
    %li= link_to "Support", support_path, :nav_item => :support
    %li= link_to "About", about_path, :nav_item => :about
    